# exports make available to parent charts
exports:
  # kafka ssl
  # The key and truststores file data are the base64 encoded contents of the files. YOU MUST PROVIDE THE DATA BASE64 encoded
  # The passwords will be base64enc by the secret include
  kafka:
    ssl:
      enabled: false
      trustStoreFileData:
      keyStoreFileData:
      trustStorePassword:
      keyStorePassword:
      keyPassword:
    sasl:
      enabled: false
      # keyTabData is the base64 enecoded contents kerberos keytab file is using kerberos 
      keyTabData: |-
      # jaasFileData is the contents of the kafka jaas file
      jaasFileData: |-
      #GSSAP, SCRAM or PLAIN
      mechanism: 

