
kind: Secret
metadata:
  name: {{ include "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ include "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
data:
  hazelcast.group.password: {{ .Values.groupPassword | b64enc }}