apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "fullname" . | quote }}
  labels:
    app: {{ include "fullname" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: "lenses"
    lenses.io/app: "{{ include "fullname" . }}"
    lenses.io/app.type: lenses
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "fullname" . | quote }}
        component: "lenses"
        hostPort: {{ .Values.restPort | quote }}
        containerPort: {{ .Values.restPort | quote }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        prometheus.io/path: "/metrics"
    spec:
      volumes:             
        - name: secrets
          secret:
            secretName: {{ include "fullname" . | quote }}
            items:
              - key: security.conf
                path: security.conf
              - key: lenses.keytab
                path: lenses.keytab 
              - key: keytab
                path: keytab                               
              - key: client.keystore.jks
                path: client.keystore.jks
              - key: client.truststore.jks 
                path: client.truststore.jks
              - key: processor.client.keystore.jks
                path: processor.client.keystore.jks
              - key: processor.client.truststore.jks
                path: processor.client.truststore.jks
              - key: jaas.conf
                path: jaas.conf
              - key: processor.jaas.conf
                path: processor.jaas.conf
              - key: processor.keytab
                path: processor.keytab
              - key: registry.keytab
                path: registry.keytab
        - name: krb
          configMap:
            name: {{ include "fullname" . | quote }}
        {{- if .Values.persistence.enabled }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-claim" (include "fullname" .)) }}
        {{- end }}
      serviceAccountName: {{ .Values.serviceAccount }}      
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{if .Values.image.tag }}{{ .Values.image.tag }}{{else}}{{ .Chart.AppVersion }}{{end}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.restPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.restPort }}
          initialDelaySeconds: 120
          periodSeconds: 3
        volumeMounts:
          - name: secrets
            mountPath: "/mnt/secrets"
          - name: secrets
            mountPath: "/etc/keytab"
            subPath: "keytab"  
          - name: secrets
            mountPath: "/etc/registry.keytab"
            subPath: "registry.keytab"  
          - name: krb
            mountPath: "/etc/krb5.conf"
            subPath: "krb5.conf"
          - name: krb
            mountPath: "/etc/processor.krb5.conf"
            subPath: "processor.krb5.conf"
          {{- if .Values.persistence.enabled }}
          - name: storage
            mountPath: "/data/storage"
          {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}     
        env:
        {{- if .Values.lenses.licenseUrl }} 
        - name: LICENSE_URL
          value: {{ .Values.lenses.licenseUrl }}
        {{- end }}
        {{- if .Values.lenses.kafka.sasl.enabled }}
        - name: LENSES_OPTS
          value: "-Djava.security.krb5.conf=/etc/krb5.conf -Djava.security.auth.login.config=/mnt/secrets/jaas.conf"
        {{- end }}
        {{- if.Values.lenses.jvm.heapOpts}}
        - name: LENSES_HEAP_OPTS
          value: {{ .Values.lenses.jvm.heapOpts | quote }}
        {{- end }}  
        {{- if.Values.lenses.jvm.logBackOpts}}
        - name: LENSES_LOG4J_OPTS
          value: {{ .Values.lenses.jvm.logBackOpts | quote }}
        {{- end }} 
        {{- if.Values.lenses.jvm.performanceOpts}}
        - name: LENSES_PERFORMANCE_OPTS
          value: {{ .Values.lenses.jvm.performanceOpts | quote }}
        {{- end }}
        - name: LICENSE
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key: "license" 
        - name: LENSES_PORT
          value: {{ .Values.restPort | quote }}
        - name: LENSES_JMX_PORT
          value: "9101"
        - name: LENSES_KAFKA_BROKERS
          value: {{ include "bootstrapBrokers" . | quote }}
        {{- if.Values.lenses.kafka.metrics}}
        - name: LENSES_KAFKA_METRICS
          value: |-
{{ include "kafkaMetrics" . | indent 12 }}
        {{- end }}
        {{- if.Values.lenses.jmxBrokers}}
        - name: LENSES_JMX_BROKERS
          values: |-
{{ include "jmxBrokers" . | indent 12 }}
        {{- end }}
        {{- if .Values.lenses.zookeepers.enabled }}
        - name: LENSES_ZOOKEEPER_HOSTS
          value: |-
{{ include "zookeepers" . | indent 12 }}
        {{- end }}

        {{- if .Values.lenses.zookeepers.chroot }}
        - name: LENSES_ZOOKEEPER_CHROOT
          value: {{ .Values.lenses.zookeepers.chroot | quote }}
        {{- end }}

        # Schema Registries
        - name: LENSES_SCHEMA_REGISTRY_URLS
          value: |-
{{ include "registries" . | indent 12 }}
        - name: LENSES_SCHEMA_REGISTRY_MODE
          value: {{ default "" .Values.lenses.schemaRegistries.mode | quote }}
        {{- if .Values.lenses.schemaRegistries.security.kerberos.enabled }}
        - name: LENSES_SCHEMA_REGISTRY_KERBEROS
          value: {{ default "false" .Values.lenses.schemaRegistries.security.kerberos.enabled | quote }}
        - name: LENSES_SCHEMA_REGISTRY_KEYTAB
          value: "/etc/registry.keytab"
        - name: LENSES_SCHEMA_REGISTRY_PRINCIPAL
          value: {{ .Values.lenses.schemaRegistries.security.kerberos.principal | quote }}
        - name: LENSES_SCHEMA_REGISTRY_SERVICE_NAME
          value: {{ .Values.lenses.schemaRegistries.security.kerberos.serviceName | quote }}
        {{- end }}
        # from secrets as might contain basic auth credentials
        - name: LENSES_KAFKA_CONNECT_CLUSTERS
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key: "connect.clusters"

        - name: LENSES_ALERT_CONSUMERS_LAG_THRESHOLD
          value: {{ .Values.lenses.alerts.consumersLagThreshold | quote }}
        {{- if .Values.lenses.alerts.enabled }}
        - name: LENSES_ALERT_PLUGINS
          value: |-
{{ include "alertPlugins" . | indent 12 }}
        {{- end }}
        {{- if .Values.lenses.grafanaUrl }}
        - name: LENSES_GRAFANA
          value: {{ .Values.lenses.grafanaUrl | quote }}  
        {{- end }}

        # lenses topics      
        - name: LENSES_TOPICS_AUDITS
          value: {{ include "auditTopic" . | quote }}
        - name: LENSES_TOPICS_METRICS
          value: {{ include "metricTopic" . | quote }}  
        - name: LENSES_TOPICS_PROFILES
          value: {{ include "profileTopic" . | quote }} 
        - name: LENSES_TOPICS_PROCESSORS
          value: {{ include "processorTopic" . | quote }}           
        - name: LENSES_TOPICS_CLUSTER
          value: {{ include "clusterTopic" . | quote }} 
        - name: LENSES_TOPICS_ALERTS_STORAGE
          value: {{ include "alertTopic" . | quote }}
        - name: LENSES_TOPICS_ALERTS_SETTINGS
          value: {{ include "alertSettingTopic" . | quote }} 
        - name: LENSES_TOPICS_LSQL_STORAGE
          value: {{ include "lsqlTopic" . | quote }} 
        - name: LENSES_TOPICS_METADATA
          value: {{ include "metadataTopic" . | quote }}                                                           
        - name: LENSES_TOPICS_EXTERNAL_TOPOLOGY
          value: {{ include "topologyTopic" . | quote }}    
        {{- if .Values.lenses.kafka.jmxPort }}
        - name: LENSES_JMX_BROKER_PORT
          value: {{ .Values.lenses.kafka.jmxPort | quote }}
        {{- end }}
          
        # Kubernetes Processors
        - name: LENSES_SQL_EXECUTION_MODE
          value: {{ .Values.lenses.sql.mode | quote }}

        # user secrets
        - name: LENSES_SECRET_FILE
          value: "/mnt/secrets/security.conf"
        - name: LENSES_SCHEMA_REGISTRY_AUTH
          value: {{ default "" .Values.lenses.schemaRegistries.security.authType | quote }}
        - name: LENSES_SCHEMA_REGISTRY_USERNAME
          value: {{ default "" .Values.lenses.schemaRegistries.security.username | quote }}
        - name: LENSES_SCHEMA_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key: "schema.registry.password"
        - name: LENSES_KAFKA_SETTINGS_PRODUCER_BASIC_AUTH_CREDENTIALS_SOURCE
          value: {{ default "" .Values.lenses.schemaRegistries.security.authType | quote }}
        - name: LENSES_KAFKA_SETTINGS_PRODUCER_BASIC_AUTH_USER_INFO
          value: {{ include "kafkaSchemaBasicAuth" . | quote }}
        - name: LENSES_KAFKA_SETTINGS_CONSUMER_BASIC_AUTH_CREDENTIALS_SOURCE
          value: {{ default "" .Values.lenses.schemaRegistries.security.authType | quote }}
        - name: LENSES_KAFKA_SETTINGS_CONSUMER_BASIC_AUTH_USER_INFO
          value: {{ include "kafkaSchemaBasicAuth" . | quote }}

        # ssl/sasl
        - name: LENSES_KAFKA_SETTINGS_CONSUMER_SECURITY_PROTOCOL
          value: {{ include "securityProtocol" . | quote }}
        - name: LENSES_KAFKA_SETTINGS_PRODUCER_SECURITY_PROTOCOL
          value: {{ include "securityProtocol" . | quote }}  
        - name: LENSES_KAFKA_SETTINGS_CONSUMER_SASL_MECHANISM
          value: {{ default "GSSAPI" .Values.lenses.kafka.sasl.mechanism | quote }}    
        - name: LENSES_KAFKA_SETTINGS_PRODUCER_SASL_MECHANISM
          value: {{ default "GSSAPI" .Values.lenses.kafka.sasl.mechanism | quote }}
        {{- if and .Values.lenses.kafka.ssl.trustStoreFileData .Values.lenses.kafka.ssl.enabled }}
        - name: LENSES_KAFKA_SETTINGS_CONSUMER_SSL_TRUSTSTORE_LOCATION
          value: "/mnt/secrets/client.truststore.jks"
        - name: LENSES_KAFKA_SETTINGS_PRODUCER_SSL_TRUSTSTORE_LOCATION
          value: "/mnt/secrets/client.truststore.jks"          
        {{- end -}}
        {{- if and .Values.lenses.kafka.ssl.keyStoreFileData .Values.lenses.kafka.ssl.enabled }}
        - name: LENSES_KAFKA_SETTINGS_CONSUMER_SSL_KEYSTORE_LOCATION
          value: "/mnt/secrets/client.keystore.jks"
        - name: LENSES_KAFKA_SETTINGS_PRODUCER_SSL_KEYSTORE_LOCATION
          value: "/mnt/secrets/client.keystore.jks"          
        {{- end -}}
        {{- if and .Values.lenses.kafka.ssl.trustStorePassword .Values.lenses.kafka.ssl.enabled }}
        - name: LENSES_KAFKA_SETTINGS_CONSUMER_SSL_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "client.truststore.password" 
        - name: LENSES_KAFKA_SETTINGS_PRODUCER_SSL_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "client.truststore.password"               
        {{- end -}}  
        {{- if and .Values.lenses.kafka.ssl.keyStorePassword .Values.lenses.kafka.ssl.enabled }}                             
        - name: LENSES_KAFKA_SETTINGS_CONSUMER_SSL_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "client.keystore.password"
        - name: LENSES_KAFKA_SETTINGS_PRODUCER_SSL_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "client.keystore.password"              
        {{- end -}}  
        {{- if and .Values.lenses.kafka.ssl.keyPassword .Values.lenses.kafka.ssl.enabled }}              
        - name: LENSES_KAFKA_SETTINGS_CONSUMER_SSL_KEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "client.key.password"  
        - name: LENSES_KAFKA_SETTINGS_PRODUCER_SSL_KEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "client.key.password"                  
        {{- end }} 

        # Kubernetes processors
        {{- if eq .Values.lenses.sql.mode "KUBERNETES"}}
        - name: LENSES_KUBERNETES_PROCESSOR_IMAGE_NAME
          value: {{ .Values.lenses.sql.processorImage | quote }}
        - name: LENSES_KUBERNETES_PROCESSOR_IMAGE_TAG
          value: {{ .Values.lenses.sql.processorImageTag | quote }}
        - name: LENSES_KUBERNETES_PROCESSOR_IMAGE_TAG
          value: {{ .Values.lenses.sql.processorImageTag | quote }}
        - name: LENSES_KUBERNETES_PROCESSOR_SCHEMA_REGISTRY_KEYTAB
          value: "/etc/registry.keytab"
        - name: LENSES_KUBERNETES_PROCESSOR_HEAP
          value: {{ .Values.lenses.sql.heap | quote }}
        - name: LENSES_KUBERNETES_PROCESSOR_MEM_LIMIT
          value: {{ .Values.lenses.sql.memLimit | quote }}
        - name: LENSES_KUBERNETES_PROCESSOR_MEM_REQUEST
          value: {{ .Values.lenses.sql.memRequest | quote }}
        - name: LENSES_KUBERNETES_PROCESSOR_SECURITY_PROTOCOL
          value: {{ include "securityProtocol" . | quote }}
        - name: LENSES_KUBERNETES_PROCESSOR_SASL_MECHANISM
          value: {{ default "GSSAPI" .Values.lenses.kafka.sasl.mechanism | quote }}
        - name: LENSES_KUBERNETES_PROCESSOR_JAAS
          value: "/mnt/secrets/processor.jaas.conf"
        - name: LENSES_KUBERNETES_PROCESSOR_KRB5
          value: "/etc/processor.krb5.conf"
        - name: LENSES_KUBERNETES_PROCESSOR_SETTINGS_BASIC_AUTH_CREDENTIALS_SOURCE
          value: {{ default "" .Values.lenses.schemaRegistries.security.authType | quote }}
        - name: LENSES_KUBERNETES_PROCESSOR_SETTINGS_BASIC_AUTH_USER_INFO
          value: {{ include "kafkaSchemaBasicAuth" . | quote }}
        - name: LENSES_KUBERNETES_PROCESSOR_SCHEMA_REGISTRY_SETTINGS_BASIC_AUTH_CREDENTIALS_SOURCE
          value: {{ default "" .Values.lenses.schemaRegistries.security.authType | quote }}
        - name: LENSES_KUBERNETES_PROCESSOR_SCHEMA_REGISTRY_SETTINGS_BASIC_AUTH_AUTH_USER_INFO
          value: {{ include "kafkaSchemaBasicAuth" . | quote }}

        {{- if and .Values.lenses.sql.ssl.trustStoreFileData .Values.lenses.kafka.ssl.enabled }}   
        - name: LENSES_KUBERNETES_PROCESSOR_KAFKA_SETTINGS_SSL_TRUSTSTORE_LOCATION
          value: "/mnt/secrets/processor.client.truststore.jks"
        {{- end }}  
        {{- if and .Values.lenses.sql.ssl.keyStoreFileData .Values.lenses.kafka.ssl.enabled }}         
        - name: LENSES_KUBERNETES_PROCESSOR_KAFKA_SETTINGS_SSL_KEYSTORE_LOCATION
          value: "/mnt/secrets/processor.client.keystore.jks"
        {{- end -}} 
        {{- if and .Values.lenses.sql.ssl.trustStorePassword .Values.lenses.kafka.ssl.enabled }} 
        - name: LENSES_KUBERNETES_PROCESSOR_KAFKA_SETTINGS_SSL_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "processor.client.truststore.password"
        {{- end -}}  
        {{- if and .Values.lenses.sql.ssl.keyStorePassword .Values.lenses.kafka.ssl.enabled }}            
        - name: LENSES_KUBERNETES_PROCESSOR_KAFKA_SETTINGS_SSL_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
             name: {{ include "fullname" . | quote }}
             key:  "processor.client.keystore.password"
        {{- end -}} 
        {{- if and .Values.lenses.sql.ssl.keyPassword .Values.lenses.kafka.ssl.enabled }}                    
        - name: LENSES_KUBERNETES_PROCESSOR_KAFKA_SETTINGS_SSL_KEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . | quote }}
              key:  "processor.client.key.password"
        {{- end }}
        {{- end }}

        # extras configs
        {{- range $key, $value := .Values.lenses.configOverrides }}
        - name: {{ printf "%s" $key | replace "." "_" | upper | quote }}
          value: {{ $value | quote }}
        {{- end }}

        - name: LT_PACKAGE
          value: "helm"

        - name: LT_PACKAGE_VERSION
          value: "{{ .Chart.Version }}"
