# secretsRef Landscaper secrets ref
secretsRef:
name: "__REQUIRED__"
# storageClass name of the storage class
storageClassName: "__REQUIRED__"
# capacity of the storage e.g. 10Gi
capacity: "__REQUIRED__"
# Access mode, read and write from many pods
accessMode: "ReadWriteMany"
# accesMode Conditional Azure file configuration if secretsRef is set. Secret name is the secrets reference provided by the landscaper
azureFile:
  shareName: "__REQUIRED__"
  readOnly: false