
kind: Secret
metadata:
  name: {{ include "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ include "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"    
  annotations:
    "helm.sh/hook": pre-install
data:
  connect.rethink.password: {{ .Values.password | b64enc }}
  connect.rethink.rethink.auth.key: {{ .Values.rethinkAuth | b64enc }}
  {{- if .Values.tlsEnabled }}
  ca.crt: {{ .Values.rethinkCertFileData | b64enc }}
  {{- end -}}