
kind: Secret
metadata:
  name: {{ include "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ include "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
data:
  connect.coap.password: {{ .Values.password | b64enc  }}
  {{- if .Values.sslEnabled }}
  connect.coap.truststore.pass: {{ .Values.trustStorePass | b64enc }}
  connect.coap.keystore.pass: {{ .Values.keyStorePass | b64enc }}
  client.truststore.jks: {{ .Values.trustStoreFileData }}
  client.keystore.jks: {{ .Values.keyStoreFileData }}
  private-key.pem: {{ toYaml .Values.privateKeyFileData | b64enc  | indent 2 }}
  public-key.pem: {{ toYaml .Values.publicKeyFileData | b64enc  | indent 2 }}
  {{- end -}}
