apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "fullname" . }}"
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: "{{ include "fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}" 
    lenses: lenses-secret   
  annotations:
    "helm.sh/hook": pre-install
data:
  client-cert.pem: {{ .Values.tlsCert | b64enc }}
  ca-cert.pem: {{ .Values.tlsCaCert | b64enc }}
  client-key.pem: {{ .Values.tlsKey | b64enc }}
