apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fullname" . }}
  labels:
    app: {{ include "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    lenses.io/app: {{ include "fullname" . }}    
    lenses.io/app.type: lenses-connector
    lenses.io/pipeline: {{ .Values.monitoring.pipeline | quote }}    
spec:
  selector:
    matchLabels:
      app: {{ include "fullname" . | quote }}
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ template "fullname" . }}-headless
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  template:
    metadata:
      labels:
        app: {{ include "fullname" . }}
        hostPort: {{ .Values.restPort | quote }}
        containerPort: {{ .Values.restPort | quote }}
        lenses.io/app: {{ include "fullname" . }}        
        lenses.io/pipeline: {{ .Values.monitoring.pipeline | quote }}
        lenses.io/app.type: lenses-connector
      annotations:
        prometheus.io/scrape: {{ .Values.monitoring.enabled | quote }}
        prometheus.io/port: {{ .Values.monitoring.port | quote }}
        prometheus.io/path: {{ .Values.monitoring.path | quote }}
    spec:
      {{- if or .Values.kafka.ssl.enabled .Values.kafka.sasl.enabled .Values.sslEnabled }} 
      volumes:
        {{- if .Values.sslEnabled }}
        - name: connector-secrets
          secret:
            secretName: {{ include "fullname" . }}-kafka-secrets
            defaultMode: 256
            items:
              - key: client.keystore.jks
                path: client.keystore.jks
              - key: client.truststore.jks 
                path: client.truststore.jks 
        {{- end }}        
        {{- if or .Values.kafka.ssl.enabled .Values.kafka.sasl.enabled }}        
        - name: kafka-secrets
          secret:
            secretName: {{ include "fullname" . }}
            defaultMode: 256
            items:
              {{- if .Values.kafka.ssl.enabled }}
              - key: client.keystore.jks
                path: client.keystore.jks
              - key: client.truststore.jks 
                path: client.truststore.jks
              {{- end }}  
              {{- if .Values.kafka.sasl.enabled }}
              - key: jaas.conf
                path: jaas.conf
              - key: keytab
                path: keytab  
              {{- end }} 
        {{- if eq .Values.kafka.sasl.mechanism "GSSAPI" }}
        - name: krb
          configMap:
            name: {{ include "fullname" . | quote }}
        {{- end }}              
        {{- end }} 
      {{- end }}            
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.restPort }}
        livenessProbe:
          exec:
            command:
            - /opt/lenses/bin/liveliness
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- if or .Values.kafka.ssl.enabled .Values.kafka.sasl.enabled .Values.sslEnabled }} 
        volumeMounts:
          {{- if .Values.sslEnabled }}
          - name: connector-secrets
            mountPath: "/mnt/connector-secrets" 
          {{- end }}  
          {{- if or .Values.kafka.ssl.enabled .Values.kafka.sasl.enabled }}
          - name: kafka-secrets
            mountPath: "/mnt/secrets" 
          {{- if eq .Values.kafka.sasl.mechanism "GSSAPI" }}
          - name: krb
            mountPath: "/etc/krb5.conf"
            subPath: "krb5.conf"
          {{- end }}            
          {{- end }}  
        {{- end }}         
        env:
        # JVM Heap Allowance
        - name: KAFKA_HEAP_OPTS
          value: -Xmx{{ .Values.javaHeap }}
        - name: CONNECT_LOG4J_ROOT_LOGLEVEL
          value: {{ .Values.logLevel | quote }}
        - name: CONNECT_GROUP_ID
          value: {{ .Values.clusterName | quote }}
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: {{ include "bootstrapBrokers" . | quote }}
        - name: CONNECT_REST_PORT
          value: {{ .Values.restPort | quote }}
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: "connect-{{ .Values.clusterName }}-configs"
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: "connect-{{ .Values.clusterName }}-offsets"
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: "connect-{{ .Values.clusterName }}-statuses"
        - name: CONNECT_KEY_CONVERTER
          value: "{{ .Values.keyConverter }}"
        - name: CONNECT_VALUE_CONVERTER
          value: "{{ .Values.valueConverter }}"
        - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
          value: {{ include "registries" . | quote }}
        - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
          value: {{ include "registries" . | quote }}
        - name: CONNECT_INTERNAL_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_INTERNAL_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name:  CONNECT_PLUGIN_PATH
          value: "/opt/lenses/lib"
        - name:  CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
          value: {{ .Values.kafka.replicationFactor | quote }}
        - name:  CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
          value: {{ .Values.kafka.replicationFactor | quote }} 
        - name:  CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
          value: {{ .Values.kafka.replicationFactor | quote }}  

        - name: CONNECT_PRODUCER_SECURITY_PROTOCOL
          value: {{ include "securityProtocol" . | quote }}
        - name: CONNECT_CONSUMER_SECURITY_PROTOCOL
          value: {{ include "securityProtocol" . | quote }}          
        - name: CONNECTOR_PRODUCER_SECURITY_PROTOCOL
          value: {{ include "securityProtocol" . | quote }}  
        - name: CONNECTOR_CONSUMER_SECURITY_PROTOCOL
          value: {{ include "securityProtocol" . | quote }}  

        {{- if .Values.kafka.sasl.enabled }}
        - name: KAFKA_OPTS
          value: "-Djava.security.auth.login.config=/mnt/secrets/jaas.conf -Xmx{{ .Values.javaHeap }}"        
        - name: CONNECT_PRODUCER_SASL_MECHANISM
          value: {{ default "GSSAPI" .Values.kafka.sasl.mechanism | quote }}
        - name: CONNECT_CONSUMER_SASL_MECHANISM
          value: {{ default "GSSAPI" .Values.kafka.sasl.mechanism | quote }}     
        - name: CONNECTOR_PRODUCER_SASL_MECHANISM
          value: {{ default "GSSAPI" .Values.kafka.sasl.mechanism | quote }}  
        - name: CONNECTOR_CONSUMER_SASL_MECHANISM
          value: {{ default "GSSAPI" .Values.kafka.sasl.mechanism | quote }}      
        {{- end }}  
   
        {{- if .Values.kafka.ssl.enabled }}
        - name: CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION
          value: "/mnt/secrets/client.truststore.jks"
        - name: CONNECT_CONSUMER_SSL_TRUSTSTORE_LOCATION
          value: "/mnt/secrets/client.truststore.jks"
        - name: CONNECT_PRODUCER_SSL_KEYSTORE_LOCATION
          value: "/mnt/secrets/client.keystore.jks"
        - name: CONNECT_CONSUMER_SSL_KEYSTORE_LOCATION
          value: "/mnt/secrets/client.keystore.jks"
        - name: WORKER_CONNECT_SECRET_PRODUCER_SSL_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ include "fullname" . }}-kafka-secrets"
              key:  "client.truststore.password"
        - name: WORKER_CONNECT_SECRET_CONSUMER_SSL_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ include "fullname" . }}-kafka-secrets"
              key:  "client.truststore.password"                                  
        - name: WORKER_CONNECT_SECRET_PRODUCER_SSL_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ include "fullname" . }}-kafka-secrets"
              key:  "client.keystore.password"
        - name: WORKER_CONNECT_SECRET_CONSUMER_SSL_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ include "fullname" . }}-kafka-secrets"
              key:  "client.keystore.password"              

        - name: CONNECTOR_PRODUCER_SSL_TRUSTSTORE_LOCATION
          value: "/mnt/secrets/client.truststore.jks"
        - name: CONNECTOR_CONSUMER_SSL_TRUSTSTORE_LOCATION
          value: "/mnt/secrets/client.truststore.jks"
        - name: CONNECTOR_PRODUCER_SSL_KEYSTORE_LOCATION
          value: "/mnt/secrets/client.keystore.jks"
        - name: CONNECTOR_CONSUMER_SSL_KEYSTORE_LOCATION
          value: "/mnt/secrets/client.keystore.jks"
        - name: SECRET_PRODUCER_SSL_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ include "fullname" . }}-kafka-secrets"
              key:  "client.truststore.password"
        - name: SECRET_CONSUMER_SSL_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ include "fullname" . }}-kafka-secrets"
              key:  "client.truststore.password"                                  
        - name: SECRET_PRODUCER_SSL_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ include "fullname" . }}-kafka-secrets"
              key:  "client.keystore.password"
        - name: SECRET_CONSUMER_SSL_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ include "fullname" . }}-kafka-secrets"
              key:  "client.keystore.password"  
        {{- end }}

        # Connector properties
        - name: SECRETS_PROVIDER
          value: {{ .Values.secretsProvider | quote }}        
        - name: CONNECTOR_NAME
          value: {{ .Values.applicationId | quote }}
        - name: CONNECTOR_GROUP_ID
          value: {{ .Values.applicationId | quote }}
        - name: CONNECTOR_CONNECTOR_CLASS
          value: {{ .Values.connectorClass | quote }}
        - name: CONNECTOR_TASKS_MAX
          value: {{ .Values.replicaCount | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_KCQL
          value: {{ .Values.kcql | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_MAX_RETRIES
          value: {{ .Values.maxRetries | quote }}          
        - name: CONNECTOR_CONNECT_CASSANDRA_ERROR_POLICY
          value: {{ .Values.errorPolicy | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_RETRY_INTERVAL
          value: {{ .Values.retryInterval | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_IMPORT_ALLOW_FILTERING
          value: {{ .Values.importAllowFiltering | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_SLICE_DURATION
          value: {{ .Values.sliceDuration | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_SLICE_DELAY_MS
          value: {{ .Values.sliceDelayMs | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_INITIAL_OFFSET
          value: {{ .Values.initialOffset | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_TASK_BUFFER_SIZE
          value: {{ .Values.taskBufferSize | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_IMPORT_POLL_INTERVAL
          value: {{ .Values.importPollInterval | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_DELETE_ENABLED
          value: {{ .Values.deleteEnabled | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_DELETE_STATEMENT
          value: {{ .Values.deleteStatement | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_DELETE_STRUCT_FLDS
          value: {{ .Values.deleteStructFlds | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_SSL_ENABLED
          value: {{ .Values.sslEnabled | quote }} 

        #cassandra
        - name: CONNECTOR_CONNECT_CASSANDRA_KEY_SPACE
          value: {{ .Values.keySpace | quote }} 
        - name: CONNECTOR_CONNECT_CASSANDRA_CONTACT_POINTS
          value: {{ .Values.contactPoints | quote }}                   
        - name: CONNECTOR_CONNECT_CASSANDRA_USERNAME
          value: {{ .Values.username | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . }}
              key:  "connect.cassandra.password"
        - name: CONNECTOR_CONNECT_CASSANDRA_CONSISTENCY_LEVEL
          value: {{ .Values.consistencyLevel | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_PORT
          value: {{ .Values.port | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_FETCH_SIZE
          value: {{ .Values.fetchSize | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_SSL_ENABLED
          value: {{ .Values.sslEnabled | quote }}   

        {{- if .Values.sslEnabled }}
        - name: CONNECTOR_CONNECT_CASSANDRA_TRUST_STORE_TYPE
          value: {{ .Values.trustStoreType | quote }} 
        - name: CONNECTOR_CONNECT_CASSANDRA_TRUST_STORE_PATH
          value: "/mnt/connector-secrets/client.truststore.jks" 
        - name: SECRET_CONNECT_CASSANDRA_TRUST_STORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . }}
              key:  "connect.cassandra.trust.store.password"           
        - name: CONNECTOR_CONNECT_CASSANDRA_KEY_STORE_TYPE
          value: {{ .Values.keyStoreType | quote }}       
        - name: CONNECTOR_CONNECT_CASSANDRA_KEY_STORE_PATH
          value: "/mnt/connector-secrets/client.keystore.jks"
        - name: SECRET_CONNECT_CASSANDRA_KEY_STORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" . }}
              key:  "connect.cassandra.key.store.password"
        - name: CONNECTOR_CONNECT_CASSANDRA_SSL_CLIENT_CERT_AUTH
          value: {{ .Values.sslClientCertAuth | quote }}
       {{- end }}
        - name: CONNECTOR_CONNECT_CASSANDRA_MAPPING_COLLECTION_TO_JSON
          value: {{.Values.mappingCollectionToJson | quote}}