kind: Service
apiVersion: v1
metadata:
  name: kafka
spec:
  selector:
    app: test-kafka-connect-blockchain
  ports:
  - name: broker
    protocol: TCP
    port: 9092
  - name: connect
    protocol: TCP
    port: 8083
  - name: zk
    protocol: TCP
    port: 2181
  - name: zk-jmx
    protocol: TCP
    port: 9585
  - name: schema
    protocol: TCP
    port: 8081
  - name: schema-jmx
    protocol: TCP
    port: 9582
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-kafka-connect-blockchain
  labels:
    app: test-kafka-connect-blockchain
spec:
  selector:
    matchLabels:
      app: test-kafka-connect-blockchain
  replicas: 1
  template:
    metadata:
      name: test-deployment
      labels:
        app: test-kafka-connect-blockchain
    spec:
      containers:
      - name: kafka
        image: landoop/fast-data-dev
        env:
          - name: ADV_HOST
            valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          - name: FORWARDLOGS
            value: "0"
          - name: SAMPLEDATA
            value: "0"
          - name: RUNTESTS
            value: "0"
          - name: CONNECTORS
            value: "blockchain"
          - name: CONNECTOR_GROUP_ID
            value: "blockchain-test"
        ports:
          - name: broker
            containerPort: 9092
          - name: connect
            containerPort: 8083
          - name: zk
            containerPort: 2181
          - name: zk-jmx
            containerPort: 9585
          - name: schema
            containerPort: 8081
          - name: schema-jmx
            containerPort: 9582