apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        hostPort: {{ .Values.restPort | quote }}
        containerPort: {{ .Values.restPort | quote }}
        pipeline: {{ .Values.monitoring.pipeline | quote }}
        lenses: lenses-connector
        lenses-user: {{ .Values.lensesUser}}
      annotations:
        prometheus.io/scrape: {{ .Values.monitoring.enabled | quote }}
        prometheus.io/port: {{ .Values.monitoring.port | quote }}
        prometheus.io/path: {{ .Values.monitoring.path | quote }}
        configTopic: "{connect-{{ .Values.clusterName }}-configs"
        statusTopic: "{connect-{{ .Values.clusterName }}-statuses"
        offsetTopic: "{connect-{{ .Values.clusterName }}-offsets"
    spec:
      volumes:
        # Use for SSL keystores and trust stores from host path or persistent volumes
        {{- if .Values.ssl.enabled}}
        - name: connect-ssl
        {{- if .Values.ssl.persistentVolumes.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.ssl.persistentVolumes.existingClaim }}{{ .Values.ssl.persistentVolumes.existingClaim }}{{- else }}{{ template "fullname" . }}{{- end }}
        {{- else}}
          hostPath:
            path: {{ .Values.ssl.path }}
        {{- end -}}
        {{- end -}}
        # Get TKS from secrets
        {{- if .Values.tls.enabled }}
        - name: connect-tls
          secret:
            secretName: {{ .Values.secretsRef | quote }}
        {{- end }}
        # Get avro schemas from config-map
        {{- if .Values.avroSchemas }}
        - name: connect-avro-schemas
          configMap:
            name: {{ template "fullname" . }}
        {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.restPort }}
        livenessProbe:
          exec:
            command:
            - /etc/landoop/liveliness.sh
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
          {{- if .Values.ssl.enabled }}
          - mountPath: /connector-ssl
            name: connect-ssl
          {{- end -}}
          {{- if .Values.tls.enabled }}
          - mountPath: /connector-tls
            name: connect-tls
          {{- end }}
          {{- if .Values.avroSchemas }}
          - mountPath: /connector-avro-schemas
            name: connect-avro-schemas
          {{- end }}
        env:
        # JVM Heap Allowance
        - name: KAFKA_HEAP_OPTS
          value: -Xmx{{ .Values.javaHeap }}
        - name: CONNECT_LOG4J_ROOT_LOGLEVEL
          value: {{ .Values.logLevel | quote }}
        - name: CONNECT_GROUP_ID
          value: {{ .Values.clusterName | quote }}
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: {{ .Values.bootstrapServers | quote }}
        - name: CONNECT_REST_PORT
          value: {{ .Values.restPort | quote }}
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: "{connect-{{ .Values.clusterName }}-configs"
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: "connect-{{ .Values.clusterName }}-offsets"
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: "{connect-{{ .Values.clusterName }}-statuses"
        - name: CONNECT_KEY_CONVERTER
          value: "{{ .Values.keyConverter }}"
        - name: CONNECT_VALUE_CONVERTER
          value: "{{ .Values.valueConverter }}"
        - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
          value: {{ .Values.schemaRegistryURL | quote }}
        - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
          value: {{ .Values.schemaRegistryURL | quote }}
        - name: CONNECT_INTERNAL_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_INTERNAL_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name:  CONNECT_PLUGIN_PATH
          value: "/etc/landoop/jars"

  
        # Connector properties
        - name: CONNECTOR_NAME
          value: {{ .Values.applicationId | quote }}
        - name: CONNECTOR_GROUP_ID
          value: {{ .Values.applicationId | quote }}
        - name: CONNECTOR_CONNECTOR_CLASS
          value: {{ .Values.connectorClass | quote }}
        - name: CONNECTOR_TASKS_MAX
          value: {{ .Values.tasksMax | quote }}

        - name: CONNECTOR_CONNECT_CASSANDRA_KEY_STORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretsRef | quote }}
              key:  {{ .Values.keyStorePasswordKey }}
        - name: CONNECTOR_CONNECT_CASSANDRA_KEY_SPACE
          value: {{ .Values.keySpace | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_CONTACT_POINTS
          value: {{ .Values.contactPoints | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_SSL_ENABLED
          value: {{ .Values.sslEnabled | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_CONSISTENCY_LEVEL
          value: {{ .Values.consistencyLevel | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_TRUST_STORE_TYPE
          value: {{ .Values.trustStoreType | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_USERNAME
          value: {{ .Values.username | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_TRUST_STORE_PATH
          value: {{ .Values.trustStorePath | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_KEY_STORE_PATH
          value: {{ .Values.keyStorePath | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_PORT
          value: {{ .Values.port | quote }}
        - name: CONNECTOR_CONNECT_PROGRESS_ENABLED
          value: {{ .Values.progressEnabled | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_SSL_CLIENT_CERT_AUTH
          value: {{ .Values.sslClientCertAuth | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretsRef | quote }}
              key:  {{ .Values.passwordKey }}
        - name: CONNECTOR_CONNECT_CASSANDRA_KCQL
          value: {{ .Values.kcql | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_MAX_RETRIES
          value: {{ .Values.maxRetries | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_ERROR_POLICY
          value: {{ .Values.errorPolicy | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_RETRY_INTERVAL
          value: {{ .Values.retryInterval | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_KEY_STORE_TYPE
          value: {{ .Values.keyStoreType | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_TRUST_STORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretsRef | quote }}
              key:  {{ .Values.trustStorePasswordKey }}
        - name: CONNECTOR_CONNECT_CASSANDRA_THREADPOOL_SIZE
          value: {{ .Values.threadpoolSize | quote }}
        - name: CONNECTOR_CONNECT_CASSANDRA_FETCH_SIZE
          value: {{ .Values.fetchSize | quote }}
