{{- if or .Values.kafka.ssl.enabled .Values.kafka.sasl.enabled }} 
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-kafka-secrets
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
  annotations:
    "helm.sh/hook": pre-install
data:
  {{- if .Values.kafka.ssl.enabled }}
  client.truststore.jks: {{ .Values.kafka.ssl.trustStoreFileData }}
  client.keystore.jks: {{ .Values.kafka.ssl.keyStoreFileData }}
  client.truststore.password: {{ .Values.kafka.ssl.trustStorePassword }}
  client.keystore.password: {{ .Values.kafka.ssl.keyStorePassword }}
  {{- end -}}
  {{- if .Values.kafka.sasl.enabled }}
  jaas.conf: {{ .Values.kafka.sasl.jaasFileData }}
  {{- end -}}
{{- end -}}