apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ include "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    lenses: lenses-secret
  annotations:
    "helm.sh/hook": pre-install
data:
  connect.cassandra.password: {{ .Values.password | b64enc }}
  {{- if .Values.sslEnabled }}
  connect.cassandra.key.store.password: {{ .Values.keyStorePassword | b64enc }}
  connect.cassandra.trust.store.password: {{ .Values.trustStorePassword | b64enc }}
  client.truststore.jks: {{ .Values.trustStoreFileData }}
  client.keystore.jks: {{ .Values.keyStoreFileData }}
  {{- end -}}
